### ISSUE TITLE
Blank White Screen, Mac OS

### ISSUE THREAD

**Issue by soten355** [andrewringler/video-2-slit-scan#16]
Hello,

I only have a blank white screen when I open the program on Mac OS, Big Sur.

I gave the program full disk access and nothing has changed.

Any tips?

**Comment by andrewringler** [comment]
OK. Thank you for reporting. Yes, I have confirmed unfortunately that the app does not work on MacOS Big Sur. Currently the app is using Java 8 and Processing version 3. I am not sure Java 8 runs on Big Sur and I am pretty sure Processing version 3 does not run on Big Sur. At the very least I would need to update to Processing v 4, and it appears a function I am relying on, creating a PImage from a BufferedImage is missing in P4. I will let you know if I make any progress but unfortunately I am not actively working on this application.

**Comment by zandr** [comment]
I don't think either of those things are the issue. Java 8 is still current (release 301), and I just ran slit_cam (from https://slitcam.com/) under both Processing 3.5.4 and 4.0b1 on an M1 MacBook Air running Big Sur.

I'll try a local build and see if it behaves any differently. I'd love something easier to use than slit_cam. :)

**Comment by andrewringler** [comment]
I have just released a new version of the tool [v0.2.6](https://github.com/andrewringler/video-2-slit-scan/releases/tag/v0.2.6) that now supports Apple M1 computers. There is now a separate download for Intel and Silicon computers. I switched to Processing v4 and I am now also using an embedded jlink JRE in the installers. I think this issue should now be resolved. @soten355 @zandr. Thanks.
